services:
    shop_service_filter:
        class:  'Application\ShopBundle\Service\FilterService'
        arguments:    ['@core_manager_factory']

    shop_service_tree:
        class:  'Application\ShopBundle\Service\CategoryTreeService'
        calls:
            - [setManagerFactory, [@core_manager_factory]]
