user_admin:
    resource: "@ApplicationUserBundle/Resources/config/routing/admin.yml"
    prefix:  /admin

user_profile:
    pattern:  /profile
    defaults: { _controller: ApplicationUserBundle:Profile:index }
