shop_admin_brand:
    resource: "@ApplicationShopBundle/Controller/Admin/BrandController.php"
    type:     annotation

shop_admin_category:
    resource: "@ApplicationShopBundle/Controller/Admin/CategoryController.php"
    type:     annotation

shop_admin_property:
    resource: "@ApplicationShopBundle/Controller/Admin/PropertyController.php"
    type:     annotation

shop_admin_product:
    resource: "@ApplicationShopBundle/Controller/Admin/ProductController.php"
    type:     annotation

shop_admin_prototype:
    resource: "@ApplicationShopBundle/Controller/Admin/PrototypeController.php"
    type:     annotation