news_admin_news:
    resource: "@ApplicationNewsBundle/Controller/Admin/NewsController.php"
    type:     annotation

news_admin_section:
    resource: "@ApplicationNewsBundle/Controller/Admin/SectionController.php"
    type:     annotation