gallery_admin_gallery:
    resource: "@ApplicationGalleryBundle/Controller/Admin/ImageController.php"
    type:     annotation

gallery_admin_place:
    resource: "@ApplicationGalleryBundle/Controller/Admin/SectionController.php"
    type:     annotation