services:
    admin_form_type_image:
        class: 'Application\AdminBundle\Form\Type\ImageType'
        tags:
            - { name: form.type, alias: image }
        calls:
            - [setUploaderHelper, ['@vich_uploader.templating.helper.uploader_helper']]