services:
    banner_twig_extention:
        class: 'Application\BannerBundle\Twig\BannerExtension'
        calls:
            - [setManagerFactory, [@core_manager_factory]]
        tags:
            - { name: twig.extension }