web_home:
    pattern:  /
    defaults: { _controller: ApplicationWebBundle:Default:index }

web_gallery:
    pattern:  /gallery
    defaults: { _controller: ApplicationWebBundle:Gallery:index }

web_contact:
    pattern:  /contacts
    defaults: { _controller: ApplicationWebBundle:Contact:index }

web_service:
    pattern:  /service
    defaults: { _controller: ApplicationWebBundle:Service:index }

web_partners:
    pattern:  /partners
    defaults: { _controller: ApplicationWebBundle:Partner:index }

web_partners_ritmo:
    pattern:  /partners/ritmo
    defaults: { _controller: ApplicationWebBundle:Partner:ritmo }

web_partners_mempex:
    pattern:  /partners/mempex
    defaults: { _controller: ApplicationWebBundle:Partner:mempex }

web_partners_center_plastics:
    pattern:  /partners/center-plastics
    defaults: { _controller: ApplicationWebBundle:Partner:centerplastics }