parameters:
    #gallery_manager_image
    gallery_manager_image.class: '\Application\GalleryBundle\Entity\Image'
    gallery_manager_image.repository: 'ApplicationGalleryBundle:Image'
    gallery_manager_image.where:
       'e.isActive = :active':
            active : 1
    gallery_manager_image.order:
       name : desc

    #gallery_manager_section
    gallery_manager_section.class: '\Application\GalleryBundle\Entity\Section'
    gallery_manager_section.repository: 'ApplicationGalleryBundle:Section'
    gallery_manager_section.where:
       'e.isActive = :active':
            active : 1
    gallery_manager_section.order:
       name : desc

services:
    gallery_manager_image:
        class:        'Application\GalleryBundle\Manager\ImageManager'
        scope:        prototype
        parent:       core_manager_standard
        arguments:    [%gallery_manager_image.class%, %gallery_manager_image.repository%, %gallery_manager_image.where%, %gallery_manager_image.order%]

    gallery_manager_section:
        scope:        prototype
        parent:       core_manager_standard
        arguments:    [%gallery_manager_section.class%, %gallery_manager_section.repository%, %gallery_manager_section.where%, %gallery_manager_section.order%]